In [10]:
import numpy as np

vector = np.array([1,2,3])
print(vector * 5)

matrices = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

v_sum = np.sum(vector)
v_mean = np.mean(vector)
v_max = np.max(vector)

print("Mean", v_mean)
print("Sum", v_sum)
print("Max", v_max)


print(matrices)
print(matrices.shape)
print(matrices.dot(vector))

zeros = np.zeros((3, 2))
print(zeros)

random = np.random.randn(5, 2)
print(random)

[ 5 10 15]
Mean 2.0
Sum 6
Max 3
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[14 32 50]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[-0.04378108 -0.15826676]
 [-1.48418348  0.00324985]
 [ 0.03798445  0.1459685 ]
 [-0.67750708 -0.0227418 ]
 [ 0.23466368  1.48296944]]


In [11]:
full_diagram = """

DAY 9 — Vectors, Matrices & NumPy

1. Concepts
   - Vector = 1D array of numbers
   - Matrix = 2D table of numbers
   - AI uses matrices for images, text, neural nets

2. NumPy Basics
   - import numpy as np
   - Create arrays
   - Check shape
   - Element-wise operations
   - Matrix multiplication (.dot)

3. Why NumPy?
   - Fast (C-level speed)
   - Supports linear algebra
   - Used in ML libraries

4. Operations
   - Addition
   - Scalar multiply
   - Dot product
   - Matrix × vector

5. Practical Use in ML
   - Dataset = matrix
   - Features = vector
   - Weights = matrix
   - NN layer = W @ x


"""

print(full_diagram)



DAY 9 — Vectors, Matrices & NumPy

1. Concepts
   - Vector = 1D array of numbers
   - Matrix = 2D table of numbers
   - AI uses matrices for images, text, neural nets

2. NumPy Basics
   - import numpy as np
   - Create arrays
   - Check shape
   - Element-wise operations
   - Matrix multiplication (.dot)

3. Why NumPy?
   - Fast (C-level speed)
   - Supports linear algebra
   - Used in ML libraries

4. Operations
   - Addition
   - Scalar multiply
   - Dot product
   - Matrix × vector

5. Practical Use in ML
   - Dataset = matrix
   - Features = vector
   - Weights = matrix
   - NN layer = W @ x



