In [ ]:
tasks = """
    Task 1

Create a 3×3 matrix and:

print shape

print total size

print 2nd column
"""



In [12]:
# task 1
import numpy as np
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(np.size(matrix))
print(np.shape(matrix))

# task 2
print(matrix[1,:])

# task 3
a = np.array([1,2,3])
print(a + 10)
print(a ** 2)
print(a * a)
print(a / 2)

# task 4
x = np.array([10,20,30,40])
x_norm = (x - min(x)) / (max(x) - min(x))
print(x_norm)


9
(3, 3)
[4 5 6]
[11 12 13]
[1 4 9]
[1 4 9]
[0.5 1.  1.5]
[0.         0.33333333 0.66666667 1.        ]
