In [1]:
full_diagram = """

DAY 12 — Advanced NumPy
│
├── 1. Reshape
│     ├── change shape
│     ├── -1 auto dimension
│     └── flatten()
│
├── 2. Transpose
│     ├── swap axes
│     └── used in neural nets
│
└── 3. Broadcasting
      ├── rules
      ├── scalar broadcasting
      ├── vector + matrix
      └── ML usage (bias, normalization)


"""

print(full_diagram)



DAY 12 — Advanced NumPy
│
├── 1. Reshape
│     ├── change shape
│     ├── -1 auto dimension
│     └── flatten()
│
├── 2. Transpose
│     ├── swap axes
│     └── used in neural nets
│
└── 3. Broadcasting
      ├── rules
      ├── scalar broadcasting
      ├── vector + matrix
      └── ML usage (bias, normalization)





In [ ]:
import numpy as np

numbers = np.arange(1, 13)
print(numbers.reshape(3, 4))

m = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

flat_m = m.flatten()
print(flat_m)

A = np.array([[2,4,6],
              [1,3,5]])

transferred = A.T
print(transferred)


my_list = np.array([[1,2,3],
 [4,5,6]])

nums = np.array([10,20, 30])

print(my_list + nums)
import numpy as np

X = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

# 1️⃣ Find row-wise minimums → shape (2, 1)
row_min = X.min(axis=1, keepdims=True)

# 2️⃣ Find row-wise maximums → shape (2, 1)
row_max = X.max(axis=1, keepdims=True)

# 3️⃣ Apply normalization using broadcasting
X_norm = (X - row_min) / (row_max - row_min)

print("Normalized X:\n", X_norm)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4 5 6 7 8 9]
[[2 1]
 [4 3]
 [6 5]]
[[11 22 33]
 [14 25 36]]
Normalized X:
 [[0.  0.5 1. ]
 [0.  0.5 1. ]]
